version: "3"

services:
  mysql:
    container_name: mysql
    hostname: mysql
    restart: always
    image: mysql:8.0.36-debian
    env_file: .env
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      start_period: 10s
      interval: 10s
      timeout: 10s
      retries: 3
